### ISSUE TITLE
Suggestion: An awesome mockup

### ISSUE THREAD

**Issue by thachngopl** [hrdwrrsk/tetra-gtk-theme#4]
Hi there. Thank you for your work. Tetra is an awesome theme.
There is an awesome mockuo similar to elementaryOS here: https://www.deviantart.com/bassultra/art/eGTK-Mockup-Kit-339505098
It would be nice if there is another theme based on this mockup. Thank you

**Comment by hrdwrrsk** [comment]
Nope for creating mockups like that, since i prefer to use a 'real - working stuff' in gtk+ css code with some experimentation and some testing before it's released


I also have an unreleased gtk+ theme that worked since late 2016/early 2017, it's based on zukitre, but remains for personal use and feels unfinished, it's to 'bridge' with famous 'Ciliora-Secunda/Tertia' GNOME shell theme
